# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from canopy.openapi.configuration import Configuration


class AdditionalTests(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'create_user': 'bool',
        'create_study': 'bool',
        'complete_study': 'bool'
    }

    attribute_map = {
        'create_user': 'createUser',
        'create_study': 'createStudy',
        'complete_study': 'completeStudy'
    }

    def __init__(self, create_user=None, create_study=None, complete_study=None, local_vars_configuration=None):  # noqa: E501
        """AdditionalTests - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._create_user = None
        self._create_study = None
        self._complete_study = None
        self.discriminator = None

        if create_user is not None:
            self.create_user = create_user
        if create_study is not None:
            self.create_study = create_study
        if complete_study is not None:
            self.complete_study = complete_study

    @property
    def create_user(self):
        """Gets the create_user of this AdditionalTests.  # noqa: E501


        :return: The create_user of this AdditionalTests.  # noqa: E501
        :rtype: bool
        """
        return self._create_user

    @create_user.setter
    def create_user(self, create_user):
        """Sets the create_user of this AdditionalTests.


        :param create_user: The create_user of this AdditionalTests.  # noqa: E501
        :type: bool
        """

        self._create_user = create_user

    @property
    def create_study(self):
        """Gets the create_study of this AdditionalTests.  # noqa: E501


        :return: The create_study of this AdditionalTests.  # noqa: E501
        :rtype: bool
        """
        return self._create_study

    @create_study.setter
    def create_study(self, create_study):
        """Sets the create_study of this AdditionalTests.


        :param create_study: The create_study of this AdditionalTests.  # noqa: E501
        :type: bool
        """

        self._create_study = create_study

    @property
    def complete_study(self):
        """Gets the complete_study of this AdditionalTests.  # noqa: E501


        :return: The complete_study of this AdditionalTests.  # noqa: E501
        :rtype: bool
        """
        return self._complete_study

    @complete_study.setter
    def complete_study(self, complete_study):
        """Sets the complete_study of this AdditionalTests.


        :param complete_study: The complete_study of this AdditionalTests.  # noqa: E501
        :type: bool
        """

        self._complete_study = complete_study

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdditionalTests):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdditionalTests):
            return True

        return self.to_dict() != other.to_dict()
