# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from canopy.openapi.configuration import Configuration


class CollatedWorksheetLabels(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'label_definitions': 'CollatedWorksheetLabelsLabelDefinitions',
        'configs': 'list[ConfigResolvedLabels]',
        'studies': 'list[StudyResolvedLabels]'
    }

    attribute_map = {
        'label_definitions': 'labelDefinitions',
        'configs': 'configs',
        'studies': 'studies'
    }

    def __init__(self, label_definitions=None, configs=None, studies=None, local_vars_configuration=None):  # noqa: E501
        """CollatedWorksheetLabels - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._label_definitions = None
        self._configs = None
        self._studies = None
        self.discriminator = None

        self.label_definitions = label_definitions
        self.configs = configs
        self.studies = studies

    @property
    def label_definitions(self):
        """Gets the label_definitions of this CollatedWorksheetLabels.  # noqa: E501


        :return: The label_definitions of this CollatedWorksheetLabels.  # noqa: E501
        :rtype: CollatedWorksheetLabelsLabelDefinitions
        """
        return self._label_definitions

    @label_definitions.setter
    def label_definitions(self, label_definitions):
        """Sets the label_definitions of this CollatedWorksheetLabels.


        :param label_definitions: The label_definitions of this CollatedWorksheetLabels.  # noqa: E501
        :type label_definitions: CollatedWorksheetLabelsLabelDefinitions
        """
        if self.local_vars_configuration.client_side_validation and label_definitions is None:  # noqa: E501
            raise ValueError("Invalid value for `label_definitions`, must not be `None`")  # noqa: E501

        self._label_definitions = label_definitions

    @property
    def configs(self):
        """Gets the configs of this CollatedWorksheetLabels.  # noqa: E501


        :return: The configs of this CollatedWorksheetLabels.  # noqa: E501
        :rtype: list[ConfigResolvedLabels]
        """
        return self._configs

    @configs.setter
    def configs(self, configs):
        """Sets the configs of this CollatedWorksheetLabels.


        :param configs: The configs of this CollatedWorksheetLabels.  # noqa: E501
        :type configs: list[ConfigResolvedLabels]
        """
        if self.local_vars_configuration.client_side_validation and configs is None:  # noqa: E501
            raise ValueError("Invalid value for `configs`, must not be `None`")  # noqa: E501

        self._configs = configs

    @property
    def studies(self):
        """Gets the studies of this CollatedWorksheetLabels.  # noqa: E501


        :return: The studies of this CollatedWorksheetLabels.  # noqa: E501
        :rtype: list[StudyResolvedLabels]
        """
        return self._studies

    @studies.setter
    def studies(self, studies):
        """Sets the studies of this CollatedWorksheetLabels.


        :param studies: The studies of this CollatedWorksheetLabels.  # noqa: E501
        :type studies: list[StudyResolvedLabels]
        """
        if self.local_vars_configuration.client_side_validation and studies is None:  # noqa: E501
            raise ValueError("Invalid value for `studies`, must not be `None`")  # noqa: E501

        self._studies = studies

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CollatedWorksheetLabels):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CollatedWorksheetLabels):
            return True

        return self.to_dict() != other.to_dict()
