# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from canopy.openapi.configuration import Configuration


class EncryptionReEncryptRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'data': 'object',
        'sim_version': 'str',
        'decrypting_tenant_short_name': 'str'
    }

    attribute_map = {
        'data': 'data',
        'sim_version': 'simVersion',
        'decrypting_tenant_short_name': 'decryptingTenantShortName'
    }

    def __init__(self, data=None, sim_version=None, decrypting_tenant_short_name=None, local_vars_configuration=None):  # noqa: E501
        """EncryptionReEncryptRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._data = None
        self._sim_version = None
        self._decrypting_tenant_short_name = None
        self.discriminator = None

        self.data = data
        self.sim_version = sim_version
        self.decrypting_tenant_short_name = decrypting_tenant_short_name

    @property
    def data(self):
        """Gets the data of this EncryptionReEncryptRequest.  # noqa: E501

        The data to be re-encrypted.  # noqa: E501

        :return: The data of this EncryptionReEncryptRequest.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this EncryptionReEncryptRequest.

        The data to be re-encrypted.  # noqa: E501

        :param data: The data of this EncryptionReEncryptRequest.  # noqa: E501
        :type data: object
        """

        self._data = data

    @property
    def sim_version(self):
        """Gets the sim_version of this EncryptionReEncryptRequest.  # noqa: E501

        The sim version of the data being re-encrypted.              This should match the sim version of the data, but also determines the encryption key used.  # noqa: E501

        :return: The sim_version of this EncryptionReEncryptRequest.  # noqa: E501
        :rtype: str
        """
        return self._sim_version

    @sim_version.setter
    def sim_version(self, sim_version):
        """Sets the sim_version of this EncryptionReEncryptRequest.

        The sim version of the data being re-encrypted.              This should match the sim version of the data, but also determines the encryption key used.  # noqa: E501

        :param sim_version: The sim_version of this EncryptionReEncryptRequest.  # noqa: E501
        :type sim_version: str
        """

        self._sim_version = sim_version

    @property
    def decrypting_tenant_short_name(self):
        """Gets the decrypting_tenant_short_name of this EncryptionReEncryptRequest.  # noqa: E501

        The short name of the tenant which needs to decrypt the data.              The encryption key of this tenant will be used to encrypt the data.  # noqa: E501

        :return: The decrypting_tenant_short_name of this EncryptionReEncryptRequest.  # noqa: E501
        :rtype: str
        """
        return self._decrypting_tenant_short_name

    @decrypting_tenant_short_name.setter
    def decrypting_tenant_short_name(self, decrypting_tenant_short_name):
        """Sets the decrypting_tenant_short_name of this EncryptionReEncryptRequest.

        The short name of the tenant which needs to decrypt the data.              The encryption key of this tenant will be used to encrypt the data.  # noqa: E501

        :param decrypting_tenant_short_name: The decrypting_tenant_short_name of this EncryptionReEncryptRequest.  # noqa: E501
        :type decrypting_tenant_short_name: str
        """

        self._decrypting_tenant_short_name = decrypting_tenant_short_name

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EncryptionReEncryptRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EncryptionReEncryptRequest):
            return True

        return self.to_dict() != other.to_dict()
