# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from canopy.openapi.configuration import Configuration


class NewConfigDataConfigType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'root': 'str',
        'modifier': 'str'
    }

    attribute_map = {
        'root': 'root',
        'modifier': 'modifier'
    }

    def __init__(self, root=None, modifier=None, local_vars_configuration=None):  # noqa: E501
        """NewConfigDataConfigType - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._root = None
        self._modifier = None
        self.discriminator = None

        if root is not None:
            self.root = root
        self.modifier = modifier

    @property
    def root(self):
        """Gets the root of this NewConfigDataConfigType.  # noqa: E501


        :return: The root of this NewConfigDataConfigType.  # noqa: E501
        :rtype: str
        """
        return self._root

    @root.setter
    def root(self, root):
        """Sets the root of this NewConfigDataConfigType.


        :param root: The root of this NewConfigDataConfigType.  # noqa: E501
        :type root: str
        """

        self._root = root

    @property
    def modifier(self):
        """Gets the modifier of this NewConfigDataConfigType.  # noqa: E501


        :return: The modifier of this NewConfigDataConfigType.  # noqa: E501
        :rtype: str
        """
        return self._modifier

    @modifier.setter
    def modifier(self, modifier):
        """Sets the modifier of this NewConfigDataConfigType.


        :param modifier: The modifier of this NewConfigDataConfigType.  # noqa: E501
        :type modifier: str
        """

        self._modifier = modifier

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewConfigDataConfigType):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NewConfigDataConfigType):
            return True

        return self.to_dict() != other.to_dict()
