# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from canopy.openapi.configuration import Configuration


class RegistrationData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tenant_id': 'str',
        'email': 'str',
        'username': 'str',
        'password': 'str'
    }

    attribute_map = {
        'tenant_id': 'tenantId',
        'email': 'email',
        'username': 'username',
        'password': 'password'
    }

    def __init__(self, tenant_id=None, email=None, username=None, password=None, local_vars_configuration=None):  # noqa: E501
        """RegistrationData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._tenant_id = None
        self._email = None
        self._username = None
        self._password = None
        self.discriminator = None

        if tenant_id is not None:
            self.tenant_id = tenant_id
        if email is not None:
            self.email = email
        if username is not None:
            self.username = username
        if password is not None:
            self.password = password

    @property
    def tenant_id(self):
        """Gets the tenant_id of this RegistrationData.  # noqa: E501


        :return: The tenant_id of this RegistrationData.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this RegistrationData.


        :param tenant_id: The tenant_id of this RegistrationData.  # noqa: E501
        :type: str
        """

        self._tenant_id = tenant_id

    @property
    def email(self):
        """Gets the email of this RegistrationData.  # noqa: E501


        :return: The email of this RegistrationData.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this RegistrationData.


        :param email: The email of this RegistrationData.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def username(self):
        """Gets the username of this RegistrationData.  # noqa: E501


        :return: The username of this RegistrationData.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this RegistrationData.


        :param username: The username of this RegistrationData.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this RegistrationData.  # noqa: E501


        :return: The password of this RegistrationData.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this RegistrationData.


        :param password: The password of this RegistrationData.  # noqa: E501
        :type: str
        """

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegistrationData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RegistrationData):
            return True

        return self.to_dict() != other.to_dict()
