# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from canopy.openapi.configuration import Configuration


class ResolvedLabelNumericStatistics(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'minimum': 'float',
        'maximum': 'float',
        'mean': 'float'
    }

    attribute_map = {
        'minimum': 'minimum',
        'maximum': 'maximum',
        'mean': 'mean'
    }

    def __init__(self, minimum=None, maximum=None, mean=None, local_vars_configuration=None):  # noqa: E501
        """ResolvedLabelNumericStatistics - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._minimum = None
        self._maximum = None
        self._mean = None
        self.discriminator = None

        self.minimum = minimum
        self.maximum = maximum
        self.mean = mean

    @property
    def minimum(self):
        """Gets the minimum of this ResolvedLabelNumericStatistics.  # noqa: E501


        :return: The minimum of this ResolvedLabelNumericStatistics.  # noqa: E501
        :rtype: float
        """
        return self._minimum

    @minimum.setter
    def minimum(self, minimum):
        """Sets the minimum of this ResolvedLabelNumericStatistics.


        :param minimum: The minimum of this ResolvedLabelNumericStatistics.  # noqa: E501
        :type minimum: float
        """
        if self.local_vars_configuration.client_side_validation and minimum is None:  # noqa: E501
            raise ValueError("Invalid value for `minimum`, must not be `None`")  # noqa: E501

        self._minimum = minimum

    @property
    def maximum(self):
        """Gets the maximum of this ResolvedLabelNumericStatistics.  # noqa: E501


        :return: The maximum of this ResolvedLabelNumericStatistics.  # noqa: E501
        :rtype: float
        """
        return self._maximum

    @maximum.setter
    def maximum(self, maximum):
        """Sets the maximum of this ResolvedLabelNumericStatistics.


        :param maximum: The maximum of this ResolvedLabelNumericStatistics.  # noqa: E501
        :type maximum: float
        """
        if self.local_vars_configuration.client_side_validation and maximum is None:  # noqa: E501
            raise ValueError("Invalid value for `maximum`, must not be `None`")  # noqa: E501

        self._maximum = maximum

    @property
    def mean(self):
        """Gets the mean of this ResolvedLabelNumericStatistics.  # noqa: E501


        :return: The mean of this ResolvedLabelNumericStatistics.  # noqa: E501
        :rtype: float
        """
        return self._mean

    @mean.setter
    def mean(self, mean):
        """Sets the mean of this ResolvedLabelNumericStatistics.


        :param mean: The mean of this ResolvedLabelNumericStatistics.  # noqa: E501
        :type mean: float
        """
        if self.local_vars_configuration.client_side_validation and mean is None:  # noqa: E501
            raise ValueError("Invalid value for `mean`, must not be `None`")  # noqa: E501

        self._mean = mean

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResolvedLabelNumericStatistics):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResolvedLabelNumericStatistics):
            return True

        return self.to_dict() != other.to_dict()
