# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from canopy.openapi.configuration import Configuration


class StudyInputHash(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'hash': 'str',
        'hash_sim_versions': 'list[str]'
    }

    attribute_map = {
        'hash': 'hash',
        'hash_sim_versions': 'hashSimVersions'
    }

    def __init__(self, hash=None, hash_sim_versions=None, local_vars_configuration=None):  # noqa: E501
        """StudyInputHash - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._hash = None
        self._hash_sim_versions = None
        self.discriminator = None

        if hash is not None:
            self.hash = hash
        if hash_sim_versions is not None:
            self.hash_sim_versions = hash_sim_versions

    @property
    def hash(self):
        """Gets the hash of this StudyInputHash.  # noqa: E501


        :return: The hash of this StudyInputHash.  # noqa: E501
        :rtype: str
        """
        return self._hash

    @hash.setter
    def hash(self, hash):
        """Sets the hash of this StudyInputHash.


        :param hash: The hash of this StudyInputHash.  # noqa: E501
        :type: str
        """

        self._hash = hash

    @property
    def hash_sim_versions(self):
        """Gets the hash_sim_versions of this StudyInputHash.  # noqa: E501


        :return: The hash_sim_versions of this StudyInputHash.  # noqa: E501
        :rtype: list[str]
        """
        return self._hash_sim_versions

    @hash_sim_versions.setter
    def hash_sim_versions(self, hash_sim_versions):
        """Sets the hash_sim_versions of this StudyInputHash.


        :param hash_sim_versions: The hash_sim_versions of this StudyInputHash.  # noqa: E501
        :type: list[str]
        """

        self._hash_sim_versions = hash_sim_versions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StudyInputHash):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StudyInputHash):
            return True

        return self.to_dict() != other.to_dict()
