# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConfigResolvedLabels(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reference': 'ConfigReference',
        'hashes': 'list[ConfigHash]',
        'resolved_labels': 'list[ResolvedLabel]'
    }

    attribute_map = {
        'reference': 'reference',
        'hashes': 'hashes',
        'resolved_labels': 'resolvedLabels'
    }

    def __init__(self, reference=None, hashes=None, resolved_labels=None):  # noqa: E501
        """ConfigResolvedLabels - a model defined in Swagger"""  # noqa: E501

        self._reference = None
        self._hashes = None
        self._resolved_labels = None
        self.discriminator = None

        if reference is not None:
            self.reference = reference
        if hashes is not None:
            self.hashes = hashes
        if resolved_labels is not None:
            self.resolved_labels = resolved_labels

    @property
    def reference(self):
        """Gets the reference of this ConfigResolvedLabels.  # noqa: E501


        :return: The reference of this ConfigResolvedLabels.  # noqa: E501
        :rtype: ConfigReference
        """
        return self._reference

    @reference.setter
    def reference(self, reference):
        """Sets the reference of this ConfigResolvedLabels.


        :param reference: The reference of this ConfigResolvedLabels.  # noqa: E501
        :type: ConfigReference
        """

        self._reference = reference

    @property
    def hashes(self):
        """Gets the hashes of this ConfigResolvedLabels.  # noqa: E501


        :return: The hashes of this ConfigResolvedLabels.  # noqa: E501
        :rtype: list[ConfigHash]
        """
        return self._hashes

    @hashes.setter
    def hashes(self, hashes):
        """Sets the hashes of this ConfigResolvedLabels.


        :param hashes: The hashes of this ConfigResolvedLabels.  # noqa: E501
        :type: list[ConfigHash]
        """

        self._hashes = hashes

    @property
    def resolved_labels(self):
        """Gets the resolved_labels of this ConfigResolvedLabels.  # noqa: E501


        :return: The resolved_labels of this ConfigResolvedLabels.  # noqa: E501
        :rtype: list[ResolvedLabel]
        """
        return self._resolved_labels

    @resolved_labels.setter
    def resolved_labels(self, resolved_labels):
        """Sets the resolved_labels of this ConfigResolvedLabels.


        :param resolved_labels: The resolved_labels of this ConfigResolvedLabels.  # noqa: E501
        :type: list[ResolvedLabel]
        """

        self._resolved_labels = resolved_labels

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigResolvedLabels, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigResolvedLabels):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
