# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DocumentTypeCustomPropertyGroups(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'target': 'str',
        'properties': 'list[DocumentCustomPropertyGroup]'
    }

    attribute_map = {
        'target': 'target',
        'properties': 'properties'
    }

    def __init__(self, target=None, properties=None):  # noqa: E501
        """DocumentTypeCustomPropertyGroups - a model defined in Swagger"""  # noqa: E501

        self._target = None
        self._properties = None
        self.discriminator = None

        if target is not None:
            self.target = target
        if properties is not None:
            self.properties = properties

    @property
    def target(self):
        """Gets the target of this DocumentTypeCustomPropertyGroups.  # noqa: E501


        :return: The target of this DocumentTypeCustomPropertyGroups.  # noqa: E501
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this DocumentTypeCustomPropertyGroups.


        :param target: The target of this DocumentTypeCustomPropertyGroups.  # noqa: E501
        :type: str
        """
        allowed_values = ["car", "track", "weather", "exploration", "virtual4PostOptions", "limitSimOptions", "subLimitSimOptions", "thermalReplayOptions", "pacejkaCanopyConverterOptions", "channelInferenceOptions", "overtaking", "userMaths", "constraints", "telemetry", "files", "driveCycle", "study", "worksheet", "aircraft", "iliadBoat", "iliadCollocationOptions", "iliadVppOptions"]  # noqa: E501
        if target not in allowed_values:
            raise ValueError(
                "Invalid value for `target` ({0}), must be one of {1}"  # noqa: E501
                .format(target, allowed_values)
            )

        self._target = target

    @property
    def properties(self):
        """Gets the properties of this DocumentTypeCustomPropertyGroups.  # noqa: E501


        :return: The properties of this DocumentTypeCustomPropertyGroups.  # noqa: E501
        :rtype: list[DocumentCustomPropertyGroup]
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this DocumentTypeCustomPropertyGroups.


        :param properties: The properties of this DocumentTypeCustomPropertyGroups.  # noqa: E501
        :type: list[DocumentCustomPropertyGroup]
        """

        self._properties = properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentTypeCustomPropertyGroups, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentTypeCustomPropertyGroups):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
