# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ListFilterCondition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source': 'str',
        'name': 'str',
        'operator': 'str',
        'value': 'str'
    }

    attribute_map = {
        'source': 'source',
        'name': 'name',
        'operator': 'operator',
        'value': 'value'
    }

    def __init__(self, source=None, name=None, operator=None, value=None):  # noqa: E501
        """ListFilterCondition - a model defined in Swagger"""  # noqa: E501

        self._source = None
        self._name = None
        self._operator = None
        self._value = None
        self.discriminator = None

        if source is not None:
            self.source = source
        if name is not None:
            self.name = name
        if operator is not None:
            self.operator = operator
        if value is not None:
            self.value = value

    @property
    def source(self):
        """Gets the source of this ListFilterCondition.  # noqa: E501


        :return: The source of this ListFilterCondition.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this ListFilterCondition.


        :param source: The source of this ListFilterCondition.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def name(self):
        """Gets the name of this ListFilterCondition.  # noqa: E501


        :return: The name of this ListFilterCondition.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ListFilterCondition.


        :param name: The name of this ListFilterCondition.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def operator(self):
        """Gets the operator of this ListFilterCondition.  # noqa: E501


        :return: The operator of this ListFilterCondition.  # noqa: E501
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator):
        """Sets the operator of this ListFilterCondition.


        :param operator: The operator of this ListFilterCondition.  # noqa: E501
        :type: str
        """
        allowed_values = ["equals", "notEquals", "lessThan", "greaterThan", "lessThanOrEquals", "greaterThanOrEquals", "exists", "notExists"]  # noqa: E501
        if operator not in allowed_values:
            raise ValueError(
                "Invalid value for `operator` ({0}), must be one of {1}"  # noqa: E501
                .format(operator, allowed_values)
            )

        self._operator = operator

    @property
    def value(self):
        """Gets the value of this ListFilterCondition.  # noqa: E501


        :return: The value of this ListFilterCondition.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ListFilterCondition.


        :param value: The value of this ListFilterCondition.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListFilterCondition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListFilterCondition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
