# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StudyResolvedReference(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reference': 'StudyReference',
        'data': 'StudyResolvedReferenceData',
        'error': 'str'
    }

    attribute_map = {
        'reference': 'reference',
        'data': 'data',
        'error': 'error'
    }

    def __init__(self, reference=None, data=None, error=None):  # noqa: E501
        """StudyResolvedReference - a model defined in Swagger"""  # noqa: E501

        self._reference = None
        self._data = None
        self._error = None
        self.discriminator = None

        if reference is not None:
            self.reference = reference
        if data is not None:
            self.data = data
        if error is not None:
            self.error = error

    @property
    def reference(self):
        """Gets the reference of this StudyResolvedReference.  # noqa: E501


        :return: The reference of this StudyResolvedReference.  # noqa: E501
        :rtype: StudyReference
        """
        return self._reference

    @reference.setter
    def reference(self, reference):
        """Sets the reference of this StudyResolvedReference.


        :param reference: The reference of this StudyResolvedReference.  # noqa: E501
        :type: StudyReference
        """

        self._reference = reference

    @property
    def data(self):
        """Gets the data of this StudyResolvedReference.  # noqa: E501


        :return: The data of this StudyResolvedReference.  # noqa: E501
        :rtype: StudyResolvedReferenceData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this StudyResolvedReference.


        :param data: The data of this StudyResolvedReference.  # noqa: E501
        :type: StudyResolvedReferenceData
        """

        self._data = data

    @property
    def error(self):
        """Gets the error of this StudyResolvedReference.  # noqa: E501


        :return: The error of this StudyResolvedReference.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this StudyResolvedReference.


        :param error: The error of this StudyResolvedReference.  # noqa: E501
        :type: str
        """

        self._error = error

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StudyResolvedReference, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StudyResolvedReference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
