# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SupportSessionResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tenant_id': 'TenantId',
        'user_id': 'UserId',
        'creation_date': 'datetime',
        'message': 'str'
    }

    attribute_map = {
        'tenant_id': 'tenantId',
        'user_id': 'userId',
        'creation_date': 'creationDate',
        'message': 'message'
    }

    def __init__(self, tenant_id=None, user_id=None, creation_date=None, message=None):  # noqa: E501
        """SupportSessionResponse - a model defined in Swagger"""  # noqa: E501

        self._tenant_id = None
        self._user_id = None
        self._creation_date = None
        self._message = None
        self.discriminator = None

        if tenant_id is not None:
            self.tenant_id = tenant_id
        if user_id is not None:
            self.user_id = user_id
        if creation_date is not None:
            self.creation_date = creation_date
        if message is not None:
            self.message = message

    @property
    def tenant_id(self):
        """Gets the tenant_id of this SupportSessionResponse.  # noqa: E501


        :return: The tenant_id of this SupportSessionResponse.  # noqa: E501
        :rtype: TenantId
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this SupportSessionResponse.


        :param tenant_id: The tenant_id of this SupportSessionResponse.  # noqa: E501
        :type: TenantId
        """

        self._tenant_id = tenant_id

    @property
    def user_id(self):
        """Gets the user_id of this SupportSessionResponse.  # noqa: E501


        :return: The user_id of this SupportSessionResponse.  # noqa: E501
        :rtype: UserId
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this SupportSessionResponse.


        :param user_id: The user_id of this SupportSessionResponse.  # noqa: E501
        :type: UserId
        """

        self._user_id = user_id

    @property
    def creation_date(self):
        """Gets the creation_date of this SupportSessionResponse.  # noqa: E501


        :return: The creation_date of this SupportSessionResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """Sets the creation_date of this SupportSessionResponse.


        :param creation_date: The creation_date of this SupportSessionResponse.  # noqa: E501
        :type: datetime
        """

        self._creation_date = creation_date

    @property
    def message(self):
        """Gets the message of this SupportSessionResponse.  # noqa: E501


        :return: The message of this SupportSessionResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this SupportSessionResponse.


        :param message: The message of this SupportSessionResponse.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SupportSessionResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SupportSessionResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
