# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TenantStatistics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tenant_id': 'TenantId',
        'statistics': 'object'
    }

    attribute_map = {
        'tenant_id': 'tenantId',
        'statistics': 'statistics'
    }

    def __init__(self, tenant_id=None, statistics=None):  # noqa: E501
        """TenantStatistics - a model defined in Swagger"""  # noqa: E501

        self._tenant_id = None
        self._statistics = None
        self.discriminator = None

        if tenant_id is not None:
            self.tenant_id = tenant_id
        if statistics is not None:
            self.statistics = statistics

    @property
    def tenant_id(self):
        """Gets the tenant_id of this TenantStatistics.  # noqa: E501


        :return: The tenant_id of this TenantStatistics.  # noqa: E501
        :rtype: TenantId
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this TenantStatistics.


        :param tenant_id: The tenant_id of this TenantStatistics.  # noqa: E501
        :type: TenantId
        """

        self._tenant_id = tenant_id

    @property
    def statistics(self):
        """Gets the statistics of this TenantStatistics.  # noqa: E501


        :return: The statistics of this TenantStatistics.  # noqa: E501
        :rtype: object
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics):
        """Sets the statistics of this TenantStatistics.


        :param statistics: The statistics of this TenantStatistics.  # noqa: E501
        :type: object
        """

        self._statistics = statistics

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TenantStatistics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TenantStatistics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
