# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class WorksheetConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'config_type': 'DocumentSubType',
        'reference': 'ConfigReference',
        'inherit_reference': 'bool'
    }

    attribute_map = {
        'config_type': 'configType',
        'reference': 'reference',
        'inherit_reference': 'inheritReference'
    }

    def __init__(self, config_type=None, reference=None, inherit_reference=None):  # noqa: E501
        """WorksheetConfig - a model defined in Swagger"""  # noqa: E501

        self._config_type = None
        self._reference = None
        self._inherit_reference = None
        self.discriminator = None

        if config_type is not None:
            self.config_type = config_type
        if reference is not None:
            self.reference = reference
        if inherit_reference is not None:
            self.inherit_reference = inherit_reference

    @property
    def config_type(self):
        """Gets the config_type of this WorksheetConfig.  # noqa: E501


        :return: The config_type of this WorksheetConfig.  # noqa: E501
        :rtype: DocumentSubType
        """
        return self._config_type

    @config_type.setter
    def config_type(self, config_type):
        """Sets the config_type of this WorksheetConfig.


        :param config_type: The config_type of this WorksheetConfig.  # noqa: E501
        :type: DocumentSubType
        """

        self._config_type = config_type

    @property
    def reference(self):
        """Gets the reference of this WorksheetConfig.  # noqa: E501


        :return: The reference of this WorksheetConfig.  # noqa: E501
        :rtype: ConfigReference
        """
        return self._reference

    @reference.setter
    def reference(self, reference):
        """Sets the reference of this WorksheetConfig.


        :param reference: The reference of this WorksheetConfig.  # noqa: E501
        :type: ConfigReference
        """

        self._reference = reference

    @property
    def inherit_reference(self):
        """Gets the inherit_reference of this WorksheetConfig.  # noqa: E501


        :return: The inherit_reference of this WorksheetConfig.  # noqa: E501
        :rtype: bool
        """
        return self._inherit_reference

    @inherit_reference.setter
    def inherit_reference(self, inherit_reference):
        """Sets the inherit_reference of this WorksheetConfig.


        :param inherit_reference: The inherit_reference of this WorksheetConfig.  # noqa: E501
        :type: bool
        """

        self._inherit_reference = inherit_reference

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorksheetConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorksheetConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
