# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConfigColumnLabelDefinitions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'config_type': 'DocumentSubType',
        'labels': 'list[LabelDefinition]'
    }

    attribute_map = {
        'config_type': 'configType',
        'labels': 'labels'
    }

    def __init__(self, config_type=None, labels=None):  # noqa: E501
        """ConfigColumnLabelDefinitions - a model defined in Swagger"""  # noqa: E501

        self._config_type = None
        self._labels = None
        self.discriminator = None

        if config_type is not None:
            self.config_type = config_type
        if labels is not None:
            self.labels = labels

    @property
    def config_type(self):
        """Gets the config_type of this ConfigColumnLabelDefinitions.  # noqa: E501


        :return: The config_type of this ConfigColumnLabelDefinitions.  # noqa: E501
        :rtype: DocumentSubType
        """
        return self._config_type

    @config_type.setter
    def config_type(self, config_type):
        """Sets the config_type of this ConfigColumnLabelDefinitions.


        :param config_type: The config_type of this ConfigColumnLabelDefinitions.  # noqa: E501
        :type: DocumentSubType
        """

        self._config_type = config_type

    @property
    def labels(self):
        """Gets the labels of this ConfigColumnLabelDefinitions.  # noqa: E501


        :return: The labels of this ConfigColumnLabelDefinitions.  # noqa: E501
        :rtype: list[LabelDefinition]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this ConfigColumnLabelDefinitions.


        :param labels: The labels of this ConfigColumnLabelDefinitions.  # noqa: E501
        :type: list[LabelDefinition]
        """

        self._labels = labels

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigColumnLabelDefinitions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigColumnLabelDefinitions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
