# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SimTypeDefinition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sim_type': 'str',
        'name': 'str',
        'known_output_files': 'list[str]',
        'state': 'str',
        'input_telemetry_channels': 'SimTypeInputTelemetryChannels',
        'previous_definitions': 'list[IPreviousDefinitionSimTypeDefinition]'
    }

    attribute_map = {
        'sim_type': 'simType',
        'name': 'name',
        'known_output_files': 'knownOutputFiles',
        'state': 'state',
        'input_telemetry_channels': 'inputTelemetryChannels',
        'previous_definitions': 'previousDefinitions'
    }

    def __init__(self, sim_type=None, name=None, known_output_files=None, state=None, input_telemetry_channels=None, previous_definitions=None):  # noqa: E501
        """SimTypeDefinition - a model defined in Swagger"""  # noqa: E501

        self._sim_type = None
        self._name = None
        self._known_output_files = None
        self._state = None
        self._input_telemetry_channels = None
        self._previous_definitions = None
        self.discriminator = None

        if sim_type is not None:
            self.sim_type = sim_type
        if name is not None:
            self.name = name
        if known_output_files is not None:
            self.known_output_files = known_output_files
        if state is not None:
            self.state = state
        if input_telemetry_channels is not None:
            self.input_telemetry_channels = input_telemetry_channels
        if previous_definitions is not None:
            self.previous_definitions = previous_definitions

    @property
    def sim_type(self):
        """Gets the sim_type of this SimTypeDefinition.  # noqa: E501


        :return: The sim_type of this SimTypeDefinition.  # noqa: E501
        :rtype: str
        """
        return self._sim_type

    @sim_type.setter
    def sim_type(self, sim_type):
        """Sets the sim_type of this SimTypeDefinition.


        :param sim_type: The sim_type of this SimTypeDefinition.  # noqa: E501
        :type: str
        """
        allowed_values = ["StraightSim", "ApexSim", "QuasiStaticLap", "GenerateRacingLine", "DeploymentLap", "FailureSim", "SuccessSim", "Virtual4Post", "LimitSim", "DriveCycleSim", "DynamicLap", "DragSim", "DynamicMultiLap", "ThermalReplay", "TyreReplay", "PacejkaCanopyConverter", "AircraftSim", "ChannelInference", "Telemetry", "OvertakingLap", "TyreThermalDynamicLap", "TyreThermalDynamicMultiLap", "DynamicLapWithSLS", "DynamicLapHD", "IliadCollocation", "SubLimitSim", "ConstraintSatisfier"]  # noqa: E501
        if sim_type not in allowed_values:
            raise ValueError(
                "Invalid value for `sim_type` ({0}), must be one of {1}"  # noqa: E501
                .format(sim_type, allowed_values)
            )

        self._sim_type = sim_type

    @property
    def name(self):
        """Gets the name of this SimTypeDefinition.  # noqa: E501


        :return: The name of this SimTypeDefinition.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SimTypeDefinition.


        :param name: The name of this SimTypeDefinition.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def known_output_files(self):
        """Gets the known_output_files of this SimTypeDefinition.  # noqa: E501


        :return: The known_output_files of this SimTypeDefinition.  # noqa: E501
        :rtype: list[str]
        """
        return self._known_output_files

    @known_output_files.setter
    def known_output_files(self, known_output_files):
        """Sets the known_output_files of this SimTypeDefinition.


        :param known_output_files: The known_output_files of this SimTypeDefinition.  # noqa: E501
        :type: list[str]
        """

        self._known_output_files = known_output_files

    @property
    def state(self):
        """Gets the state of this SimTypeDefinition.  # noqa: E501


        :return: The state of this SimTypeDefinition.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this SimTypeDefinition.


        :param state: The state of this SimTypeDefinition.  # noqa: E501
        :type: str
        """
        allowed_values = ["enabled", "disabled"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def input_telemetry_channels(self):
        """Gets the input_telemetry_channels of this SimTypeDefinition.  # noqa: E501


        :return: The input_telemetry_channels of this SimTypeDefinition.  # noqa: E501
        :rtype: SimTypeInputTelemetryChannels
        """
        return self._input_telemetry_channels

    @input_telemetry_channels.setter
    def input_telemetry_channels(self, input_telemetry_channels):
        """Sets the input_telemetry_channels of this SimTypeDefinition.


        :param input_telemetry_channels: The input_telemetry_channels of this SimTypeDefinition.  # noqa: E501
        :type: SimTypeInputTelemetryChannels
        """

        self._input_telemetry_channels = input_telemetry_channels

    @property
    def previous_definitions(self):
        """Gets the previous_definitions of this SimTypeDefinition.  # noqa: E501


        :return: The previous_definitions of this SimTypeDefinition.  # noqa: E501
        :rtype: list[IPreviousDefinitionSimTypeDefinition]
        """
        return self._previous_definitions

    @previous_definitions.setter
    def previous_definitions(self, previous_definitions):
        """Sets the previous_definitions of this SimTypeDefinition.


        :param previous_definitions: The previous_definitions of this SimTypeDefinition.  # noqa: E501
        :type: list[IPreviousDefinitionSimTypeDefinition]
        """

        self._previous_definitions = previous_definitions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SimTypeDefinition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SimTypeDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
