# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UpdatedWorksheetLabelDefinitions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'label_definitions': 'LabelDefinitions'
    }

    attribute_map = {
        'label_definitions': 'labelDefinitions'
    }

    def __init__(self, label_definitions=None):  # noqa: E501
        """UpdatedWorksheetLabelDefinitions - a model defined in Swagger"""  # noqa: E501

        self._label_definitions = None
        self.discriminator = None

        if label_definitions is not None:
            self.label_definitions = label_definitions

    @property
    def label_definitions(self):
        """Gets the label_definitions of this UpdatedWorksheetLabelDefinitions.  # noqa: E501


        :return: The label_definitions of this UpdatedWorksheetLabelDefinitions.  # noqa: E501
        :rtype: LabelDefinitions
        """
        return self._label_definitions

    @label_definitions.setter
    def label_definitions(self, label_definitions):
        """Sets the label_definitions of this UpdatedWorksheetLabelDefinitions.


        :param label_definitions: The label_definitions of this UpdatedWorksheetLabelDefinitions.  # noqa: E501
        :type: LabelDefinitions
        """

        self._label_definitions = label_definitions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdatedWorksheetLabelDefinitions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdatedWorksheetLabelDefinitions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
