# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UpdatedChannelImportMappings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel_import_mappings': 'list[ChannelImportMapping]'
    }

    attribute_map = {
        'channel_import_mappings': 'channelImportMappings'
    }

    def __init__(self, channel_import_mappings=None):  # noqa: E501
        """UpdatedChannelImportMappings - a model defined in Swagger"""  # noqa: E501

        self._channel_import_mappings = None
        self.discriminator = None

        if channel_import_mappings is not None:
            self.channel_import_mappings = channel_import_mappings

    @property
    def channel_import_mappings(self):
        """Gets the channel_import_mappings of this UpdatedChannelImportMappings.  # noqa: E501


        :return: The channel_import_mappings of this UpdatedChannelImportMappings.  # noqa: E501
        :rtype: list[ChannelImportMapping]
        """
        return self._channel_import_mappings

    @channel_import_mappings.setter
    def channel_import_mappings(self, channel_import_mappings):
        """Sets the channel_import_mappings of this UpdatedChannelImportMappings.


        :param channel_import_mappings: The channel_import_mappings of this UpdatedChannelImportMappings.  # noqa: E501
        :type: list[ChannelImportMapping]
        """

        self._channel_import_mappings = channel_import_mappings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdatedChannelImportMappings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdatedChannelImportMappings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
