# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UserInformation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'UserId',
        'username': 'Username',
        'email': 'Email'
    }

    attribute_map = {
        'user_id': 'userId',
        'username': 'username',
        'email': 'email'
    }

    def __init__(self, user_id=None, username=None, email=None):  # noqa: E501
        """UserInformation - a model defined in Swagger"""  # noqa: E501

        self._user_id = None
        self._username = None
        self._email = None
        self.discriminator = None

        if user_id is not None:
            self.user_id = user_id
        if username is not None:
            self.username = username
        if email is not None:
            self.email = email

    @property
    def user_id(self):
        """Gets the user_id of this UserInformation.  # noqa: E501


        :return: The user_id of this UserInformation.  # noqa: E501
        :rtype: UserId
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this UserInformation.


        :param user_id: The user_id of this UserInformation.  # noqa: E501
        :type: UserId
        """

        self._user_id = user_id

    @property
    def username(self):
        """Gets the username of this UserInformation.  # noqa: E501


        :return: The username of this UserInformation.  # noqa: E501
        :rtype: Username
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserInformation.


        :param username: The username of this UserInformation.  # noqa: E501
        :type: Username
        """

        self._username = username

    @property
    def email(self):
        """Gets the email of this UserInformation.  # noqa: E501


        :return: The email of this UserInformation.  # noqa: E501
        :rtype: Email
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserInformation.


        :param email: The email of this UserInformation.  # noqa: E501
        :type: Email
        """

        self._email = email

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserInformation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
