# coding: utf-8

"""
    Canopy.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from canopy.swagger.api_client import ApiClient


class WorksheetApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def worksheet_get_worksheet(self, tenant_id, worksheet_id, **kwargs):  # noqa: E501
        """worksheet_get_worksheet  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.worksheet_get_worksheet(tenant_id, worksheet_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tenant_id: (required)
        :param str worksheet_id: (required)
        :param str config_version:
        :return: GetWorksheetQueryResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.worksheet_get_worksheet_with_http_info(tenant_id, worksheet_id, **kwargs)  # noqa: E501
        else:
            (data) = self.worksheet_get_worksheet_with_http_info(tenant_id, worksheet_id, **kwargs)  # noqa: E501
            return data

    def worksheet_get_worksheet_with_http_info(self, tenant_id, worksheet_id, **kwargs):  # noqa: E501
        """worksheet_get_worksheet  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.worksheet_get_worksheet_with_http_info(tenant_id, worksheet_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tenant_id: (required)
        :param str worksheet_id: (required)
        :param str config_version:
        :return: GetWorksheetQueryResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['tenant_id', 'worksheet_id', 'config_version']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method worksheet_get_worksheet" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'tenant_id' is set
        if ('tenant_id' not in params or
                params['tenant_id'] is None):
            raise ValueError("Missing the required parameter `tenant_id` when calling `worksheet_get_worksheet`")  # noqa: E501
        # verify the required parameter 'worksheet_id' is set
        if ('worksheet_id' not in params or
                params['worksheet_id'] is None):
            raise ValueError("Missing the required parameter `worksheet_id` when calling `worksheet_get_worksheet`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'tenant_id' in params:
            path_params['tenantId'] = params['tenant_id']  # noqa: E501
        if 'worksheet_id' in params:
            path_params['worksheetId'] = params['worksheet_id']  # noqa: E501

        query_params = []
        if 'config_version' in params:
            query_params.append(('configVersion', params['config_version']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/worksheets/{tenantId}/{worksheetId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetWorksheetQueryResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def worksheet_post_duplicate_configs(self, tenant_id, worksheet_id, data, **kwargs):  # noqa: E501
        """worksheet_post_duplicate_configs  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.worksheet_post_duplicate_configs(tenant_id, worksheet_id, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tenant_id: (required)
        :param str worksheet_id: (required)
        :param DuplicateConfigsData data: (required)
        :param str sim_version:
        :return: DuplicateConfigsResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.worksheet_post_duplicate_configs_with_http_info(tenant_id, worksheet_id, data, **kwargs)  # noqa: E501
        else:
            (data) = self.worksheet_post_duplicate_configs_with_http_info(tenant_id, worksheet_id, data, **kwargs)  # noqa: E501
            return data

    def worksheet_post_duplicate_configs_with_http_info(self, tenant_id, worksheet_id, data, **kwargs):  # noqa: E501
        """worksheet_post_duplicate_configs  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.worksheet_post_duplicate_configs_with_http_info(tenant_id, worksheet_id, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tenant_id: (required)
        :param str worksheet_id: (required)
        :param DuplicateConfigsData data: (required)
        :param str sim_version:
        :return: DuplicateConfigsResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['tenant_id', 'worksheet_id', 'data', 'sim_version']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method worksheet_post_duplicate_configs" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'tenant_id' is set
        if ('tenant_id' not in params or
                params['tenant_id'] is None):
            raise ValueError("Missing the required parameter `tenant_id` when calling `worksheet_post_duplicate_configs`")  # noqa: E501
        # verify the required parameter 'worksheet_id' is set
        if ('worksheet_id' not in params or
                params['worksheet_id'] is None):
            raise ValueError("Missing the required parameter `worksheet_id` when calling `worksheet_post_duplicate_configs`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `worksheet_post_duplicate_configs`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'tenant_id' in params:
            path_params['tenantId'] = params['tenant_id']  # noqa: E501
        if 'worksheet_id' in params:
            path_params['worksheetId'] = params['worksheet_id']  # noqa: E501

        query_params = []
        if 'sim_version' in params:
            query_params.append(('simVersion', params['sim_version']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/worksheets/{tenantId}/{worksheetId}/duplicate', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DuplicateConfigsResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def worksheet_post_worksheet(self, tenant_id, data, **kwargs):  # noqa: E501
        """worksheet_post_worksheet  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.worksheet_post_worksheet(tenant_id, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tenant_id: (required)
        :param NewWorksheetData data: (required)
        :return: GetWorksheetQueryResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.worksheet_post_worksheet_with_http_info(tenant_id, data, **kwargs)  # noqa: E501
        else:
            (data) = self.worksheet_post_worksheet_with_http_info(tenant_id, data, **kwargs)  # noqa: E501
            return data

    def worksheet_post_worksheet_with_http_info(self, tenant_id, data, **kwargs):  # noqa: E501
        """worksheet_post_worksheet  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.worksheet_post_worksheet_with_http_info(tenant_id, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tenant_id: (required)
        :param NewWorksheetData data: (required)
        :return: GetWorksheetQueryResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['tenant_id', 'data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method worksheet_post_worksheet" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'tenant_id' is set
        if ('tenant_id' not in params or
                params['tenant_id'] is None):
            raise ValueError("Missing the required parameter `tenant_id` when calling `worksheet_post_worksheet`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `worksheet_post_worksheet`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'tenant_id' in params:
            path_params['tenantId'] = params['tenant_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/worksheets/{tenantId}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetWorksheetQueryResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def worksheet_put_worksheet(self, tenant_id, worksheet_id, data, **kwargs):  # noqa: E501
        """worksheet_put_worksheet  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.worksheet_put_worksheet(tenant_id, worksheet_id, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tenant_id: (required)
        :param str worksheet_id: (required)
        :param UpdatedWorksheetData data: (required)
        :return: GetWorksheetQueryResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.worksheet_put_worksheet_with_http_info(tenant_id, worksheet_id, data, **kwargs)  # noqa: E501
        else:
            (data) = self.worksheet_put_worksheet_with_http_info(tenant_id, worksheet_id, data, **kwargs)  # noqa: E501
            return data

    def worksheet_put_worksheet_with_http_info(self, tenant_id, worksheet_id, data, **kwargs):  # noqa: E501
        """worksheet_put_worksheet  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.worksheet_put_worksheet_with_http_info(tenant_id, worksheet_id, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tenant_id: (required)
        :param str worksheet_id: (required)
        :param UpdatedWorksheetData data: (required)
        :return: GetWorksheetQueryResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['tenant_id', 'worksheet_id', 'data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method worksheet_put_worksheet" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'tenant_id' is set
        if ('tenant_id' not in params or
                params['tenant_id'] is None):
            raise ValueError("Missing the required parameter `tenant_id` when calling `worksheet_put_worksheet`")  # noqa: E501
        # verify the required parameter 'worksheet_id' is set
        if ('worksheet_id' not in params or
                params['worksheet_id'] is None):
            raise ValueError("Missing the required parameter `worksheet_id` when calling `worksheet_put_worksheet`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `worksheet_put_worksheet`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'tenant_id' in params:
            path_params['tenantId'] = params['tenant_id']  # noqa: E501
        if 'worksheet_id' in params:
            path_params['worksheetId'] = params['worksheet_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/worksheets/{tenantId}/{worksheetId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetWorksheetQueryResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
